name: Lint and test
on:
  push:
    branches:
      - '**'
    # tags are used for releases, no need to run tests against them as they
    # should be created only when the build is green
    tags-ignore:
      - '**'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Run tests
        run: go test -v ./...
