name: Release
on:
  release:
    types:
      # run when stable and pre-releases are published
      - published
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - darwin
          - linux
          - windows
        goarch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Build
        run: scripts/build.sh
        env:
          GITHUB_TAG: ${{ github.event.release.tag_name }}
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/*.tar.gz
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
      - run: scripts/release.sh
        env:
          GITHUB_TAG: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
